import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Me: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> ME </h1>
        <ul>
          <li>Healthy lifestyle/Gym</li>
          <li>Maths</li>
          <li>Freedom</li>
          <li>Philosophize</li>
          <li>Party / Dancing / Piano </li>
          <li>One Piece</li>
        </ul>
      </main>
      <button> GO HOME </button>
    </div>
  );
};

export default Me;
