import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ShowCaseBox from "../components/ShowcaseBox";
import styles from "../styles/Home.module.css";

const MyBusinesses: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Businesses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ShowCaseBox
        title="NFT Collection 1"
        description="Amazing NFT collection"
        image="/../public/images/my_face.jpg"
        imageAlt="An NFT from the collection"
      />

      <ShowCaseBox
        title="My Business Name"
        description="Amazing business"
        image="/../public/images/my_face.jpg"
        imageAlt="Me and my co-founder"
      />

      <ShowCaseBox
        title="NFT Collection 2"
        description="Amazing NFT collection"
        image="/../public/images/my_face.jpg"
        imageAlt="An NFT from the collection"
      />

      <Link href="/">
        <button> GO HOME </button>
      </Link>
    </div>
  );
};

export default MyBusinesses;
